chore: some
Signed-off-by: Anish Bista <anishbista053@gmail.com>

diff --git a/platform-apps/argocd/argocd-image-updater-acr-configmap.yaml b/platform-apps/argocd/argocd-image-updater-acr-configmap.yaml
--- a/platform-apps/argocd/argocd-image-updater-acr-configmap.yaml
+++ b/platform-apps/argocd/argocd-image-updater-acr-configmap.yaml
@@ -5,13 +5,13 @@ metadata:
   namespace: argocd
 data:
   acr.sh: |
-    #!/bin/sh                                                                                                                                                                                                                         │
-    REGISTRY="todoappproject.azurecr.io"                                                                                                                                                                                           │
-    USERNAME="962ab8ec-0f0f-4332-84d4-ab486070541d"                                                                                                                                                                                   │
-    PASSWORD=".NX8Q~AieOIeHXTyk5Jexg~2mtgVL6OV0krFPbyh"                                                                                                                                                                               │
-    if [ -n "$PASSWORD" ]; then                                                                                                                                                                                                       │
-      echo "$USERNAME:$PASSWORD"                                                                                                                                                                                                    │
-    else                                                                                                                                                                                                                              │
-      echo "Error: Failed to retrieve access token" >&2                                                                                                                                                                             │
-      exit 1                                                                                                                                                                                                                        │
+    #!/bin/sh
+    REGISTRY="todoappproject.azurecr.io"
+    USERNAME="962ab8ec-0f0f-4332-84d4-ab486070541d"
+    PASSWORD=".NX8Q~AieOIeHXTyk5Jexg~2mtgVL6OV0krFPbyh"
+    if [ -n "$PASSWORD" ]; then
+      echo "$USERNAME:$PASSWORD"
+    else
+      echo "Error: Failed to retrieve access token" >&2
+      exit 1
     fi
